platform :ios,'9.0'
project '/Users/shinji/Mydata/personalmarketing/english/canada/school/CICCC/subject/402/MyJuice/MyJuice_Swift/MyJuice_Swift/MyJuice_Swift.xcodeproj'
target 'MyJuice_Swift' do
use_frameworks!
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
end







